os: Visual Studio 2013

environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C %VS120COMNTOOLS%/VsDevCmd.bat"

  matrix:
    - PYTHON: "C:/Python35"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "64"

init:
  - "ECHO %APPVEYOR_SCHEDULED_BUILD% %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

before_build:
  - "cmd python test.py"

platform:
  - x86
  - Any CPU

configuration:
  - Release

matrix:
  fast_finish: true