os: Visual Studio 2013

environment:
  
  matrix:
  - PYTHON: "C:/Python35"
    PYTHON_VERSION: "3.5.2"
    PYTHON_ARCH: "64"

init:
  - "ECHO %APPVEYOR_SCHEDULED_BUILD% %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - cinst git.install tortoisehg
  - "%PYTHON%/Scripts/pip.exe install requests"
  - "%PYTHON%/Scripts/pip.exe install tqdm"

before_build"
  - cmd python build/
  
platform:
  - x86
  - Any CPU

configuration:
  - Release

matrix:
  fast_finish: true