os: Visual Studio 2013

environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C %VS120COMNTOOLS%/VsDevCmd.bat"
	
  matrix:
  - PYTHON: "C:/Python35"
    PYTHON_VERSION: "3.5.2"
    PYTHON_ARCH: "64"

init:
  - "ECHO %APPVEYOR_SCHEDULED_BUILD% %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - cinst git.install tortoisehg
  - "%PYTHON%/Scripts/pip.exe install requests"
  - "%PYTHON%/Scripts/pip.exe install tqdm"
  
before_build:
  - "cmd if defined %APPVEYOR_SCHEDULED_BUILD% ()"

  - "cmd hg clone https://bitbucket.org/xilium/xilium.cefglue -r default"
  - "cmd git clone https://github.com/jp9000/OBS.git"
  
deployment:
  - "cmd if defined %APPVEYOR_SCHEDULED_BUILD% ()"
  
build:
  - %"CMD_IN_ENV% "
  
platform:
  - x86
  - Any CPU

configuration:
  - Release

matrix:
  fast_finish: true